language: ruby
sudo: required
rvm:
  - 2.3.0
before_script:
  - psql -c 'create database sone_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/initializers/kitaguchi.rb.example config/initializers/kitaguchi.rb
before_install:
  - curl --silent --location https://github.com/pgroonga/pgroonga/raw/master/data/travis/setup.sh | sh
  - curl -O "http://iij.dl.osdn.jp/pghintplan/62456/pg_hint_plan94-1.1.3.tar.gz"
  - tar xvzf pg_hint_plan94-1.1.3.tar.gz
  - cd pg_hint_plan94-1.1.3
  - make
  - sudo make install
  - psql -c 'create extension pg_hint_plan;' -U postgres
  - cd ../
cache: bundler
addons:
  postgresql: "9.4"
notifications:
  email:
    - yune.kotomi+github@gmail.com
