language: ruby
sudo: required
rvm:
  - 2.4
  # - 2.5
before_script:
  - psql -c 'create database sone_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/initializers/kitaguchi.rb.example config/initializers/kitaguchi.rb
  - cp config/initializers/google_api.rb.example config/initializers/google_api.rb
  - RAILS_ENV=test bundle exec rails db:migrate
before_install:
  - curl --silent --location https://github.com/pgroonga/pgroonga/raw/master/data/travis/setup.sh | sh
cache: bundler
addons:
  postgresql: "9.5"
notifications:
  email:
    - yune.kotomi+github@gmail.com
